# Generated by Django 5.1.4 on 2025-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_date',
            field=models.DateField(),
        ),
    ]
